package:
  name: geos
  version: 3.5.0

source:
  fn: geos-3.5.0.tar.bz2
  url: http://download.osgeo.org/geos/geos-3.5.0.tar.bz2

build:
  number: 0

about:
  home: http://trac.osgeo.org/geos/
  license: LGPL
